CREATE TABLE IF NOT EXISTS `projeto`(
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `nome` VARCHAR(100) NOT NULL,
    `descricao` VARCHAR(100) NOT NULL,
    `valor` DECIMAL(10,2) NOT NULL,
    status ENUM('ATIVO', 'INATIVO', 'CONCLUÍDO') NOT NULL
);